### ISSUE TITLE
Warn readers?

### ISSUE THREAD

**Issue by ericlaw1979** [vcsjones/IeBHOExamples#1]
It may be worth noting that Managed Code BHOs are explicitly discouraged.
http://blogs.msdn.com/b/ieinternals/archive/2014/04/10/do-not-write-browser-extensions-toolbars-bhos-and-activex-in-managed-dotnet-code.aspx

**Comment by vcsjones** [comment]
I came to that conclusion myself:

https://vcsjones.com/2012/09/03/regrets-managed-browser-helper-objects/

But people insist on doing it anyway, so I leave the code here.

**Comment by vcsjones** [comment]
Added warning in README.
